package ai.timefold.solver.core.impl.util;

import java.io.IOException;
import java.util.Properties;

import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

@NullMarked
public final class SolverVersionUtils {

    public static final String COMMUNITY_NAME = "Timefold Solver Community Edition";
    public static final String ENTERPRISE_NAME = "Timefold Solver Enterprise Edition";
    public static final String DEVELOPMENT_SNAPSHOT = "Development Snapshot";
    public static final String CORE_GIT_PROPERTIES = "timefold-solver-core-git.properties";

    private static final String SNAPSHOT = "SNAPSHOT";

    private SolverVersionUtils() {
        // No instances.
    }

    /**
     * Strips a trailing {@code -rc-<digits>} suffix (strict: lowercase, end-anchored, exact token).
     * Everything else — {@code -beta-W}, plain releases, {@code -SNAPSHOT}, non-standard spellings —
     * is returned verbatim. {@code null} in, {@code null} out.
     */
    public static @Nullable String stripReleaseCandidate(@Nullable String version) {
        if (version == null) {
            return null;
        }
        return version.replaceAll("-rc-\\d+$", "");
    }

    /**
     * Returns the rc-stripped implementation version of the JAR that loaded the given class,
     * or {@code null} when running without a manifest (IDE, source tarball).
     */
    public static @Nullable String versionOf(Class<?> clz) {
        return stripReleaseCandidate(clz.getPackage().getImplementationVersion());
    }

    /**
     * Reads the {@code git.commit.id.abbrev} key from the named classpath resource
     * (generated by git-commit-id-maven-plugin at build time).
     * Returns {@code null} on missing resource, blank value, or any I/O failure —
     * IDE / no-git builds produce no resource and gracefully show no ref.
     */
    public static @Nullable String gitRefOf(String resourceName) {
        var cl = Thread.currentThread().getContextClassLoader();
        try (var stream = cl == null ? null : cl.getResourceAsStream(resourceName)) {
            if (stream == null) {
                return null;
            }
            var props = new Properties();
            props.load(stream);
            var ref = props.getProperty("git.commit.id.abbrev");
            return (ref == null || ref.isBlank()) ? null : ref;
        } catch (IOException e) {
            return null;
        }
    }

    /**
     * Returns the bare version string (no {@code "v"} prefix), falling back to {@code "SNAPSHOT"}.
     * This is the format expected by the model descriptor.
     */
    public static String bareVersion(Class<?> clz) {
        var version = versionOf(clz);
        return version == null ? SNAPSHOT : version;
    }

    /**
     * Returns the backward-compatible banner string (no git ref).
     * Format: {@code "<editionName> v<version>"} or {@code "<editionName> Development Snapshot"}.
     */
    public static String banner(String editionName, Class<?> versionClass) {
        var version = versionOf(versionClass);
        return version == null ? editionName + " " + DEVELOPMENT_SNAPSHOT : editionName + " v" + version;
    }

    /**
     * Returns the community banner with an optional git ref in parentheses,
     * e.g. {@code "Timefold Solver Community Edition v1.2.3 (a1b2c3d)"}.
     * Omits the parenthesised section when {@code coreRef} is {@code null}.
     */
    public static String communityBannerWithGitRef(Class<?> versionClass, @Nullable String coreRef) {
        var base = banner(COMMUNITY_NAME, versionClass);
        return coreRef != null ? "%s (%s)".formatted(base, coreRef) : base;
    }

    /**
     * Returns the enterprise banner with optional git refs in parentheses,
     * e.g. {@code "Timefold Solver Enterprise Edition v1.2.3 (core a1b2c3d, enterprise e4f5g6h)"}.
     * Omits the parenthesised section when both refs are {@code null}.
     */
    public static String enterpriseBannerWithGitRef(Class<?> versionClass, @Nullable String coreRef,
            @Nullable String enterpriseRef) {
        var base = banner(ENTERPRISE_NAME, versionClass);
        if (coreRef == null && enterpriseRef == null) {
            return base;
        }
        var sb = new StringBuilder(base).append(" (");
        if (coreRef != null) {
            sb.append("core ").append(coreRef);
        }
        if (enterpriseRef != null) {
            if (coreRef != null) {
                sb.append(", ");
            }
            sb.append("enterprise ").append(enterpriseRef);
        }
        return sb.append(")").toString();
    }

}
