version: 2

multi-ecosystem-groups:
  main:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "01:00" # Otherwise it picks a random time.
    commit-message:
      prefix: "deps: "
    labels: ["dependencies"]
  1x:
    schedule:
      interval: "cron"
      cronjob: "0 1 * * 1#1" # First Monday of the month
    commit-message:
      prefix: "deps: "
    labels: ["dependencies"]

updates:

  # Do everything in one PR, on main.
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 99
    patterns: ["*"]
    multi-ecosystem-group: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 99
    patterns: ["*"]
    multi-ecosystem-group: "main"

  # Do everything in one PR, on 1.x.
  - package-ecosystem: "maven"
    target-branch: "1.x"
    directory: "/"
    open-pull-requests-limit: 99
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    patterns: ["*"]
    multi-ecosystem-group: "1x"
  - package-ecosystem: "github-actions"
    target-branch: "1.x"
    directory: "/"
    open-pull-requests-limit: 99
    patterns: ["*"]
    multi-ecosystem-group: "1x"
