= FAQ
:doctype: book
:icons: font

== How is Timefold Solver Licensed?

Timefold Solver Community Edition is _open source_ software,
released under http://www.apache.org/licenses/LICENSE-2.0.html[the Apache License 2.0].
This license is very liberal and allows reuse for commercial purposes.
Read http://www.apache.org/foundation/licence-FAQ.html#WhatDoesItMEAN[the layman's explanation].

Timefold Solver Enterprise Edition is a commercial product
that offers xref:enterprise-edition/enterprise-edition.adoc#enterpriseEditionFeatures[additional features]
to scale out to very large datasets.
To find out more, see xref:enterprise-edition/enterprise-edition.adoc[Enterprise Edition section] of this documentation.

== Does Timefold offer pre-built models?

Timefold offers a suite of pre-built PlanningAI models designed to expedite development by addressing complex scheduling and routing challenges across various industries.
These models are built upon Timefold Solver Enterprise Edition technology and are accessible through a REST API, facilitating seamless integration into your applications.

See all available models on https://app.timefold.ai/[our platform].

== Can Timefold Solver be included in a (GraalVM) native application?

Yes. Timefold Solver has been tested with Quarkus and Spring Boot plugins to create native executables.
Native executables typically have a fast startup time and reduced memory consumption.
However, given the nature of the workloads running with the solver, these benefits are often overshadowed by slower solving speeds due to lack of JIT optimizations.

Read more about this in https://timefold.ai/blog/how-to-speed-up-timefold-solver-startup-time-by-20x-with-native-images[our blog post].