# The solver runs only for few milliseconds to avoid a HTTP timeout in this simple implementation.
quarkus.timefold.solver.termination.best-score-limit=0

# Workaround for https://github.com/quarkusio/quarkus/issues/55362
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=false