########################
# Timefold application info
########################
model.api.version=v1
timefold.application.name=Integration Tests - Simplified Employee Shift Scheduling model
timefold.application.id=integration-tests-simplified-employee-shift-scheduling
%test.ai.timefold.platform.termination.best-score-limit=0hard/0medium/*soft