[#constraintConfiguration]
= Adjusting constraints at runtime
:doctype: book
:sectnums:
:icons: font



include::../constraints-and-score/_constraint-config-shared.adoc[]

[#applyingOverrides]
[#libraryWeightOverrides]
== Applying overrides

Populate `ConstraintWeightOverrides` with the desired weights and set it on the solution before solving:

[tabs]
====
Java::
+
[source,java,options="nowrap"]
----
...

var constraintWeightOverrides = ConstraintWeightOverrides.of(
    Map.of(
        VehicleRoutingConstraintProvider.VEHICLE_CAPACITY, HardSoftScore.ofHard(2),
        VehicleRoutingConstraintProvider.SERVICE_FINISHED_AFTER_MAX_END_TIME, HardSoftScore.ZERO
    )
);

var solution = new VehicleRoutePlan();
solution.setConstraintWeightOverrides(constraintWeightOverrides);

...
----
====

The `Vehicle capacity` constraint in this planning solution has a weight of `2hard`,
as opposed to its original `1hard`.
The `Service finished after max end time` constraint has a weight of `0hard`,
and therefore will be disabled entirely.

NOTE: The string keys passed to `ConstraintWeightOverrides.of(...)` must match the constraint ID,
which is the value given to `asConstraint(...)` when building your constraints.
Using the static string constants defined in the `ConstraintProvider` eliminates this risk.

In this way, you can solve the same problem
by applying different constraint weights to each instance.
Once solved, you can compare the results
and decide which set of weights is the most suitable for your use case.

[#constraintWeightOverridesSerialization]
=== Sending overrides over the wire

Overrides are part of the planning solution,
and as such they are automatically serialized into JSON using Jackson,
assuming either of the following conditions are met:

* You use Timefold Solver's xref:integration/quarkus.adoc#integrationWithQuarkus[Quarkus integration],
* you use Timefold Solver's xref:integration/spring-boot.adoc#integrationWithSpringBoot[Spring Boot integration],
* or you directly included the `timefold-solver-jackson` module in your project.

Overrides doesn't natively deserialize from JSON back to Java objects.
This is because we have no way of knowing which `Score` implementation you may be using.
However, deserialization is easy to implement yourself by extending `AbstractConstraintWeightOverridesDeserializer`
and registering it with Jackson's `ObjectMapper`.

[#passingParametersToConstraints]
== Passing parameters to constraints

In some cases, constraints need to be parameterized
as different data sets may have different requirements for the same constraint.
For example, a constraint may have to switch the minimum required pause length between two shifts,
based on the laws of the country that the data set is dealing with.

To achieve this, you could have many variants of the same constraint in `ConstraintProvider`
and disable some of them using <<applyingOverrides,overrides>>.
To avoid the code duplication that this would have caused,
it is arguably better to have a single constraint that can be parameterized.
This section shows how to achieve this
using the xref:constraints-and-score/score-calculation.adoc#constraintStreams[Constraint Streams API].

First, create a new class to hold the parameters for the constraint.
For this document, we call it `ConstraintParameters`,
but you're free to choose any name you like:

[tabs]
====
Java::
+
[source,java,options="nowrap"]
----
public record ConstraintParameters(int minimumPauseInMinutes) {
}
----
====

Then, add a field of type `ConstraintParameters` to your planning solution
and annotate it with `@ProblemFactProperty`:

[tabs]
====
Java::
+
[source,java,options="nowrap"]
----
@PlanningSolution
public class MyPlanningSolution {

    ...

    @ProblemFactProperty
    ConstraintParameters constraintParameters;

    ...

}
----
====

This will expose the `ConstraintParameters` as a xref:domain-modeling/modeling-planning-problems.adoc#problemFacts[problem fact],
making it available to the constraints.
Finally, use the xref:constraints-and-score/score-calculation.adoc#constraintStreamsJoin[join building block]
to adjust the constraint implementation to use the parameters:

[tabs]
====
Java::
+
[source,java,options="nowrap"]
----
public class MyConstraintProvider implements ConstraintProvider {

    ...

    Constraint minimumPauseBetweenShifts(ConstraintFactory factory) {
        return factory.forEach(Shift.class)
                .join(ConstraintParameters.class)
                .penalize(HardSoftScore.ONE_HARD, (shift, parameters) -> {
                    var pauseInMinutes = shift.getPauseInMinutes();
                    return Math.max(0, pauseInMinutes - constraintParameters.minimumPauseInMinutes());
                })
                .asConstraint("Minimum pause between shifts");
    }

    ...

}
----
====
