# The model application uses ordinals for:
# - classpath application.properties (250)
# - META-INF/microprofile-config.properties (100).
#
# The SDK uses lower ordinals to give the application config the priority:
# - model-defaults application.properties (230)
# - classpath application.properties (210)
# - META-INF/microprofile-config.properties (80).
#
# Note: Cannot be implemented as ConfigSource due to issue with native: https://github.com/quarkusio/quarkus/issues/28269
config_ordinal=80

mp.openapi.filter=ai.timefold.solver.service.rest.impl.ext.OpenAPIFilter