package ai.timefold.solver.core.api.domain.valuerange;

import java.util.Iterator;
import java.util.random.RandomGenerator;

import ai.timefold.solver.core.api.domain.variable.PlanningVariable;

import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * A {@link ValueRange} that is ending. Therefore, it has a discrete (as in non-continuous) range.
 * <p>
 * Don't implement this interface directly.
 * If you can't use a collection to store the values,
 * use {@link ValueRangeFactory} to get an instance of a {@link ValueRange}.
 * 
 * @see ValueRangeFactory
 */
@NullMarked
public interface ValueRange<T> {

    /**
     * This must be consistent with {@link #getSize()}.
     *
     * @return true if the range is empty
     */
    boolean isEmpty();

    /**
     * @param value sometimes null
     * @return true if the range contains that value
     */
    boolean contains(@Nullable T value);

    /**
     * Used by uniform random selection.
     *
     * @return the exact number of elements generated by this {@link ValueRange}, always {@code >= 0}
     */
    long getSize();

    /**
     * Used by uniform random selection.
     *
     * @param index always {@code <} {@link #getSize()}
     * @return sometimes null (if {@link PlanningVariable#allowsUnassigned()} is true)
     */
    @Nullable
    T get(long index);

    /**
     * Select the elements in original (natural) order.
     */
    Iterator<T> createOriginalIterator();

    /**
     * Select in random order, but without shuffling the elements.
     * Each element might be selected multiple times.
     * Scales well because it does not require caching.
     *
     * @param workingRandom the {@link RandomGenerator} to use when any random number is needed,
     *        so runs are reproducible.
     */
    Iterator<T> createRandomIterator(RandomGenerator workingRandom);

}
