quarkus:
  timefold:
    solver:
      solver1:
        termination:
          best-score-limit: 0hard/5soft
          spent-limit: 30s
      solver2:
        termination:
          best-score-limit: 0hard/5soft
          spent-limit: 30s

