package ai.timefold.solver.model.quarkus.deployment;

import static ai.timefold.solver.model.quarkus.deployment.util.ProcessorUtils.excludeType;

import java.util.Objects;

import jakarta.enterprise.context.ApplicationScoped;

import ai.timefold.solver.model.definition.api.ModelConvertor;
import ai.timefold.solver.model.definition.api.ModelInput;
import ai.timefold.solver.model.quarkus.deployment.builditem.ModelComponentsBuildItem;
import ai.timefold.solver.model.quarkus.deployment.builditem.ModelConvertorBuildItem;
import ai.timefold.solver.model.quarkus.deployment.builditem.RestComponentsBuildItem;
import ai.timefold.solver.model.quarkus.deployment.defaults.AbstractTrivialModelConvertor;
import ai.timefold.solver.model.quarkus.deployment.util.ProcessorUtils;

import org.jboss.jandex.ClassInfo;
import org.jboss.jandex.DotName;
import org.jboss.jandex.TypeVariable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.quarkus.arc.deployment.GeneratedBeanBuildItem;
import io.quarkus.arc.deployment.GeneratedBeanGizmoAdaptor;
import io.quarkus.deployment.annotations.BuildProducer;
import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.builditem.CombinedIndexBuildItem;
import io.quarkus.gizmo.ClassCreator;
import io.quarkus.gizmo.SignatureBuilder;
import io.quarkus.gizmo.Type;

public class TimefoldModelConvertorProcessor {

    private static final Logger LOGGER = LoggerFactory.getLogger(TimefoldModelConvertorProcessor.class);

    private static final DotName MODEL_CONVERTOR = DotName.createSimple(ModelConvertor.class.getName());
    private static final DotName ABSTRACT_TRIVIAL_MODEL_CONVERTOR =
            DotName.createSimple(AbstractTrivialModelConvertor.class.getName());

    private static final String GENERATED_PACKAGE = "ai.timefold.platform.generated.convertor.";

    /**
     * Detects the last <code>ModelConvertor</code> in the class hierarchy.
     * <p>
     * If there is no such class and the <code>ModelInput</code> is the same type as <code>ModelOutput</code> and
     * <code>SolverModel</code>, a trivial model convertor is generated by extending the
     * {@link AbstractTrivialModelConvertor}.
     *
     * <pre>
     * {@code
     *
     * @ApplicationScoped
     * public class TrivialModelConvertor extends
     *         AbstractTrivialModelConvertor<Score, ModelInput, ModelConfigOverrides, SolverModel, ModelOutput> {
     *
     * }
     *
     * }
     * </pre>
     * <p>
     * If the detected class is already an {@link ApplicationScoped} bean, it retrieves it in
     * the {@link ModelConvertorBuildItem}.
     * <p>
     * If the detected class is a base <code>ModelConvertor</code> (has a single type parameter representing the
     * {@link ModelInput}),
     * generates a bean inheriting from it.
     *
     * <pre>
     * {@code
     *
     * @ApplicationScoped
     * public class ExtendedModelConvertor extends BaseModelConvertor<ExtendedModelInput> {
     *
     * }
     *
     * }
     * </pre>
     */
    @BuildStep
    ModelConvertorBuildItem generateModelConvertorBean(CombinedIndexBuildItem combinedIndex,
            ModelComponentsBuildItem modelComponentsBuildItem,
            RestComponentsBuildItem restComponentsBuildItem,
            BuildProducer<GeneratedBeanBuildItem> generatedClasses) {

        if (restComponentsBuildItem.getRestResource().isEmpty()) {
            LOGGER.debug("No rest resource found, skipping model convertor generation.");
            return null; // Skip this build step if no REST components are present
        }

        var modelConvertorOptional =
                ProcessorUtils.findLastInHierarchyType(MODEL_CONVERTOR,
                        excludeType(combinedIndex.getIndex()::getAllKnownImplementations, ABSTRACT_TRIVIAL_MODEL_CONVERTOR));
        if (modelConvertorOptional.isEmpty()) {
            if (isModelConversionTrivial(modelComponentsBuildItem)) {
                LOGGER.debug("Generating a trivial model convertor.");
                return generateTrivialModelConvertorBean(combinedIndex, modelComponentsBuildItem, generatedClasses);
            } else {
                throw new IllegalStateException(
                        "No " + MODEL_CONVERTOR.withoutPackagePrefix() + " found in the class hierarchy " +
                                "and a trivial convertor can be generated only when the model input (%s) is the same as the model output (%s) and the solver model (%s)."
                                        .formatted(modelComponentsBuildItem.getModelInput(),
                                                modelComponentsBuildItem.getModelOutput(),
                                                modelComponentsBuildItem.getSolverModel()));
            }
        }

        var modelConvertor = modelConvertorOptional.get();
        if (isConvertorReady(modelConvertor)) {
            // The detected convertor is already a bean; no need to generate a new one.
            LOGGER.debug("Found a ready model convertor ({}), skipping generation.", modelConvertor.name());
            return new ModelConvertorBuildItem(modelConvertor.name());
        }
        if (!isBaseModelConvertor(modelConvertor)) {
            throw new IllegalStateException("%s (%s) with more than 1 type parameter is not supported."
                    .formatted(MODEL_CONVERTOR.withoutPackagePrefix(), modelConvertor.name()));
        }

        LOGGER.debug("Generating model extension convertor from base convertor ({}).", modelConvertor.name());
        return generateExtendedModelConvertorBean(modelConvertor, modelComponentsBuildItem, generatedClasses);
    }

    private ModelConvertorBuildItem generateExtendedModelConvertorBean(ClassInfo modelConvertor,
            ModelComponentsBuildItem modelComponentsBuildItem, BuildProducer<GeneratedBeanBuildItem> generatedClasses) {

        TypeVariable typeVariable = modelConvertor.typeParameters().getFirst();
        if (typeVariable.bounds().size() != 1) {
            throw new IllegalStateException("%s (%s) has a type parameter with more than one bound, which is not supported."
                    .formatted(MODEL_CONVERTOR.withoutPackagePrefix(), modelConvertor.name()));
        }
        var typeVariableBound = typeVariable.bounds().getFirst();
        ClassInfo modelInput = modelComponentsBuildItem.getModelInput();
        var modelInputSuperClassType = modelInput.superClassType();

        if (!Objects.equals(typeVariableBound, modelInputSuperClassType)) {
            throw new IllegalStateException(
                    "%s (%s) has a type parameter bound that is incompatible with the %s super class (%s)."
                            .formatted(MODEL_CONVERTOR.withoutPackagePrefix(), modelConvertor.name(),
                                    DotName.createSimple(ModelInput.class).withoutPackagePrefix(),
                                    modelInputSuperClassType.name()));
        }

        // Generate a bean for the extended model convertor class with resolved type parameter (the extended model input).
        GeneratedBeanGizmoAdaptor classOutput = new GeneratedBeanGizmoAdaptor(generatedClasses);
        String modelConvertorClassName =
                GENERATED_PACKAGE + modelInput.simpleName() + "_" + ModelConvertor.class.getSimpleName();

        ClassCreator beanCreator = ClassCreator.builder().classOutput(classOutput).className(modelConvertorClassName)
                .signature(SignatureBuilder.forClass()
                        .setSuperClass(Type.parameterizedType(Type.classType(modelConvertor.name()),
                                Type.classType(modelInput.name()))))
                .build();

        beanCreator.addAnnotation(ApplicationScoped.class);
        beanCreator.close();

        return new ModelConvertorBuildItem(DotName.createSimple(modelConvertorClassName));
    }

    /**
     * Detects the last <code>ModelConvertor</code> in the class hierarchy.
     * <p>
     * If the class is already an {@link ApplicationScoped} bean, it retrieves it in
     * the {@link ModelConvertorBuildItem}.
     * <p>
     * If there is no such class and the <code>ModelInput</code> is the same type as <code>ModelOutput</code> and
     * <code>SolverModel</code>, a trivial model convertor is generated by extending the
     * {@link AbstractTrivialModelConvertor}.
     *
     */
    private ModelConvertorBuildItem generateTrivialModelConvertorBean(CombinedIndexBuildItem combinedIndex,
            ModelComponentsBuildItem modelComponentsBuildItem,
            BuildProducer<GeneratedBeanBuildItem> generatedClasses) {

        ClassInfo modelInput = modelComponentsBuildItem.getModelInput();
        ClassInfo modelOutput = modelComponentsBuildItem.getModelOutput();
        ClassInfo solverModel = modelComponentsBuildItem.getSolverModel();
        ClassInfo modelConfigOverrides = modelComponentsBuildItem.getModelConfigOverrides();

        GeneratedBeanGizmoAdaptor classOutput = new GeneratedBeanGizmoAdaptor(generatedClasses);
        String modelConvertorClassName =
                GENERATED_PACKAGE + modelInput.simpleName() + "_Trivial" + ModelConvertor.class.getSimpleName();

        ClassCreator beanCreator = ClassCreator.builder().classOutput(classOutput).className(modelConvertorClassName)
                .signature(SignatureBuilder.forClass()
                        .setSuperClass(Type.parameterizedType(Type.classType(ABSTRACT_TRIVIAL_MODEL_CONVERTOR),
                                Type.classType(modelInput.name()),
                                Type.classType(modelConfigOverrides.name()),
                                Type.classType(solverModel.name()), Type.classType(modelOutput.name()))))
                .build();

        beanCreator.addAnnotation(ApplicationScoped.class);
        beanCreator.close();

        return new ModelConvertorBuildItem(DotName.createSimple(modelConvertorClassName));
    }

    private boolean isConvertorReady(ClassInfo modelConvertor) {
        return modelConvertor.typeParameters().isEmpty()
                && modelConvertor.annotation(ApplicationScoped.class.getName()) != null;
    }

    private boolean isBaseModelConvertor(ClassInfo modelConvertor) {
        return modelConvertor.typeParameters().size() == 1;
    }

    private boolean isModelConversionTrivial(ModelComponentsBuildItem modelComponentsBuildItem) {
        return modelComponentsBuildItem.getModelInput() != null && modelComponentsBuildItem.getModelOutput() != null
                && modelComponentsBuildItem.getSolverModel() != null
                && modelComponentsBuildItem.getSolverModel().equals(modelComponentsBuildItem.getModelInput())
                && modelComponentsBuildItem.getModelInput().equals(modelComponentsBuildItem.getModelOutput());
    }
}
