package ai.timefold.solver.core.impl.domain.common.accessor.gizmo;

import java.lang.constant.ClassDesc;
import java.lang.invoke.MethodHandles;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

import io.quarkus.gizmo2.Gizmo;
import io.quarkus.gizmo2.desc.ConstructorDesc;

/**
 * Loads a class if we have the Gizmo-generated bytecode for it,
 * otherwise uses the current {@link Thread}'s context {@link ClassLoader}.
 * This implementation is thread-safe.
 */
@NullMarked
public final class GizmoClassLoader extends ClassLoader {

    private final Map<String, byte[]> classNameToBytecodeMap;
    @Nullable
    private GizmoSupportStatus gizmoSupportStatus;

    public GizmoClassLoader() {
        this(new HashMap<>());
    }

    public GizmoClassLoader(Map<String, byte[]> classNameToBytecodeMap) {
        /*
         * As parent, Gizmo needs to use the same ClassLoader that loaded its own class.
         * Otherwise, issues will arise in Quarkus with MemberAccessors which were first loaded by Quarkus
         * and then loaded again by Gizmo, which uses the default parent ClassLoader.
         */
        super(GizmoClassLoader.class.getClassLoader());
        this.classNameToBytecodeMap = classNameToBytecodeMap;
        this.gizmoSupportStatus = null;
    }

    @Override
    public String getName() {
        return "Timefold Solver Gizmo ClassLoader";
    }

    @Override
    public Class<?> findClass(String name) throws ClassNotFoundException {
        var byteCode = getBytecodeFor(name);
        if (byteCode == null) { // Not a Gizmo generated class; load from context class loader.
            return Thread.currentThread().getContextClassLoader().loadClass(name);
        } else { // Gizmo generated class.
            return defineClass(name, byteCode, 0, byteCode.length);
        }
    }

    public synchronized byte @Nullable [] getBytecodeFor(String className) {
        return classNameToBytecodeMap.get(className);
    }

    public boolean hasBytecodeFor(String className) {
        return getBytecodeFor(className) != null;
    }

    public synchronized void storeBytecode(String className, byte[] bytecode) {
        classNameToBytecodeMap.put(className, bytecode);
    }

    public boolean isGizmoSupported() {
        if (gizmoSupportStatus != null) {
            return gizmoSupportStatus == GizmoSupportStatus.SUPPORTED;
        }
        var classPackage = GizmoClassLoader.class.getPackage().getName();
        var bytecodeHolder = new AtomicReference<byte[]>();
        var gizmo = Gizmo.create((className, bytecode) -> bytecodeHolder.set(bytecode));

        var classDesc = ClassDesc.of("%s.GizmoSupportCanary".formatted(classPackage));
        gizmo.class_(classDesc,
                classCreator -> classCreator.constructor(ConstructorDesc.of(classDesc), constructorCreator -> {
                    constructorCreator.public_();
                    var this_ = constructorCreator.this_();
                    constructorCreator.body(constructor -> {
                        constructor.invokeSpecial(ConstructorDesc.of(Object.class), this_);
                        constructor.return_();
                    });
                }));
        try {
            var generatedClass = MethodHandles.lookup().defineHiddenClass(bytecodeHolder.get(), true).lookupClass();
            var instance = generatedClass.getConstructor().newInstance();
            if (instance == null) {
                // Should be impossible, but a native image might decide to optimize out
                // instance if it is unused
                gizmoSupportStatus = GizmoSupportStatus.UNSUPPORTED;
                return false;
            } else {
                gizmoSupportStatus = GizmoSupportStatus.SUPPORTED;
                return true;
            }
        } catch (Throwable e) {
            // Note: GraalVM will throw a com.oracle.svm.core.jdk.UnsupportedFeatureError
            //       on defineHiddenClass, so we catch "Throwable" here so we don't need
            //       to add GraalVM as a library
            gizmoSupportStatus = GizmoSupportStatus.UNSUPPORTED;
            return false;
        }
    }

}
