[#neighborhoodsOverview]
= Neighborhoods: Overview
:doctype: book
:sectnums:
:icons: font

IMPORTANT: The Neighborhoods API is an active research project.
It intends to simplify the creation of custom moves, eventually replacing xref:optimization-algorithms/move-selector-reference.adoc[move selectors].
The component is under development and many key features are yet to be delivered.
While we believe that the basic building blocks of the API are already stable,
we reserve the right to change the API or remove any part of it.
Your feedback is highly appreciated and will be imperative in shaping the future of this component.

[#whatIsANeighborhood]
== What is a neighborhood?

In operations research, a _neighborhood_ is a set of solutions that are "close" to a given solution.
The definition of "close" depends on the problem domain and the solution representation.
For example, in a vehicle routing problem, a neighborhood might consist of all solutions that can be reached by swapping the routes of two vehicles.
In such a case, the neighborhood would include solutions that are similar to the current solution, but with slight variations in the routes taken by the vehicles.

The operation of moving from one solution to another within a neighborhood is often referred to as a _move_. Metaheuristics such as xref:optimization-algorithms/optimization-algorithms.adoc#localSearch[local search] explore these neighborhoods to find better solutions by evaluating the moves and selecting the most promising ones,
in order to find the best solution according to xref:constraints-and-score/overview.adoc#scoreLevel[user-defined constraints].

Timefold Solver uses largely the same terminology, with one exception.
In the rest of this documentation, _a neighborhood_ refers to a set of _moves_ that can be applied to a given solution, and these moves lead the solver to neighboring solutions.
This is a distinction in name only and has no impact on the underlying concepts.

[#whatIsNeighborhoodsAPI]
== What is the Neighborhoods API?

In order for a metaheuristics-based solver such as Timefold Solver to explore the solution space effectively,
it needs a variety of move types to generate a diverse set of neighboring solutions.
For a long time, that role was fulfilled by xref:optimization-algorithms/move-selector-reference.adoc[move selectors].
However, move selectors have several limitations that make it very difficult to create complex, high-performing moves, and this can in turn lead to suboptimal solver performance.

The Neighborhoods API is a new way to define moves in Timefold Solver.
It is intended to be more flexible and easier to use than move selectors,
allowing users to create more complex yet still high-performing moves.
With this powerful new API, users will also be able to quickly prototype
and experiment with different move types,
something which the move selector API was not suitable for at all.

[#keyConcepts]
== Key concepts

The Neighborhoods API is built around a few key concepts:

Move:: The bottom-most building block of the Neighborhoods API.
A move represents a distinct type of change to the solution.
Examples include changing the value of a planning variable or swapping the values of two planning entities.
Move Stream:: Builds a set of moves, based on a declarative programming model.
It defines how to create moves for a given solution.
For example, if the move is to swap two visits for a vehicle,
the move definition would specify all pairs of visits that can be swapped for each vehicle.
Neighborhood:: A collection of move definitions that together define a full set of moves that are available for the solver to choose from.

In the following sections, we will explore each of these concepts in more detail.
