[#integrationWithSpringBoot]
= Spring Boot integration
:doctype: book
:sectnums:
:icons: font

To use Timefold Solver on Spring Boot, add the `timefold-solver-spring-boot-starter` dependency
and read the xref:quickstart/spring-boot/spring-boot-quickstart.adoc#springBootQuickStart[Spring Boot Java quick start].

[NOTE]
====
Timefold Solver Spring Boot Starter only supports Spring Boot version 4.x.
====

[#integrationWithSpringBootProperties]
== Available configuration properties

These properties are supported in Spring's `application.properties`:

:property_prefix:
:solver_name_prefix:
include::_config-properties.adoc[]

[#integrationWithSpringBootManagedResources]
== Injecting managed resources

The Spring Boot integration allows the injection of several managed resources, including `SolverConfig`, `SolverFactory`,
`SolverManager`, `SolutionManager`,  `ConstraintMetaModel` and `ConstraintVerifier`.

The `SolverConfig` resource is constructed by reading the `application.properties` file and classpath. Therefore, Domain entities (solution, entities, and constraint classes) and customized properties (`spent-limit`, etc.) for the
planning problem are identified and loaded into the solver configuration.

The available resources can be injected as follows:

[tabs]
====
Java::
+
--
[source,java,options="nowrap"]
----
@RestController
@RequestMapping("/path")
public class Resource {

    @Autowired
    SolverConfig solverConfig;

    @Autowired
    SolverFactory<Timetable> solverFactory;

    @Autowired
    SolverManager<Timetable, String> solverManager;

    @Autowired
    SolutionManager<Timetable, SimpleScore> simpleSolutionManager; // <1>

    @Autowired
    ConstraintMetaModel constraintMetaModel;

    @Autowired
    ConstraintVerifier<TimetableConstraintProvider, Timetable> constraintVerifier;

    ...
}
----
<1> You can find all the available score types in the xref:constraints-and-score/overview.adoc#scoreType[Constraints and Score] page.
--
Kotlin::
+
--
[source,kotlin,options="nowrap"]
----
@RestController
@RequestMapping("/path")
class Resource {

    @Autowired
    var solverConfig:SolverConfig?

    @Autowired
    var solverFactory:SolverFactory<Timetable>?

    @Autowired
    var solverManager:SolverManager<Timetable, String>?

    @Autowired
    var simpleSolutionManager:SolutionManager<Timetable, SimpleScore>? // <1>

    @Autowired
    var constraintMetaModel:ConstraintMetaModel? = null

    @Autowired
    var constraintVerifier:ConstraintVerifier<TimetableConstraintProvider, Timetable>? = null

    ...
}
----
<1> You can find all the available score types in the xref:constraints-and-score/overview.adoc#scoreType[Constraints and Score] page.
--
====

Timefold provides all the necessary resources for problem-solving and analysis. However, it is still possible to manually create and override the default managed resources. To create a custom `SolverManager`, use the `SolverFactory` resource.

[tabs]
====
Java::
+
--
[source,java,options="nowrap"]
----
package org.acme.schooltimetabling.rest;

import ai.timefold.solver.core.api.solver.SolverFactory;
import ai.timefold.solver.core.api.solver.SolverManager;
import ai.timefold.solver.core.config.solver.SolverManagerConfig;
import ai.timefold.solver.spring.boot.autoconfigure.TimefoldAutoConfiguration;

import org.acme.schooltimetabling.domain.Timetable;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.Primary;

@Configuration
@Import(TimefoldAutoConfiguration.class)
public class BeanProducer {

    @Bean
    @Primary
    public SolverManager<Timetable, String> overrideSolverManager(SolverFactory<Timetable> solverFactory) {
        SolverManagerConfig solverManagerConfig = new SolverManagerConfig();
        return SolverManager.create(solverFactory, solverManagerConfig);
    }
}
----
--
Kotlin::
+
--
[source,kotlin,options="nowrap"]
----
package org.acme.schooltimetabling.rest

import ai.timefold.solver.core.api.solver.SolverFactory
import ai.timefold.solver.core.api.solver.SolverManager
import ai.timefold.solver.core.config.solver.SolverManagerConfig
import ai.timefold.solver.spring.boot.autoconfigure.TimefoldAutoConfiguration
import org.acme.schooltimetabling.domain.Timetable
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Import
import org.springframework.context.annotation.Primary

@Configuration
@Import(
    TimefoldAutoConfiguration::class
)
class BeanProducer {
    @Bean
    @Primary
    fun overrideSolverManager(solverFactory: SolverFactory<Timetable>?): SolverManager<Timetable, String> {
        val solverManagerConfig = SolverManagerConfig()
        return SolverManager.create(solverFactory, solverManagerConfig)
    }
}
----
--
====

[NOTE]
====
Consider using xref:#integrationWithSpringBootMultipleResources[multiple solver configurations] instead of manually creating resources.
====

[#integrationWithSpringBootMultipleResources]
== Injecting multiple instances of `SolverManager`

Spring Boot auto-configuration module allows for defining different solver settings or even wholly distinct planning problems in the same
application. Timefold identifies each setting and provides a specific managed resource, `SolverManager`.

=== Solver configuration properties

The configuration properties for multiple solvers are defined using the namespace `timefold.solver.<solverName>`,
where `<solverName>` is the name of the related solver. The `<solverName>` property is only necessary when using multiple
solvers. For defining a single solver, refer to the xref:#integrationWithSpringBootProperties[Timefold configuration properties section].
Following properties are supported:

:property_prefix:
:solver_name_prefix: <solverName>.
include::_config-properties.adoc[]

=== Working with multiple Solvers

The different solver settings are configured in the `application.properties` file. For example, two different time
settings for `spent-limit` are defined as follows:

[source,properties,options="nowrap"]
----
# The solver "fastSolver" runs only for 5 seconds, and "regularSolver" runs for 10s
timefold.solver.fastSolver.termination.spent-limit=5s // <1>
timefold.solver.regularSolver.termination.spent-limit=10s // <2>
----
<1> Define a solver config named *fastSolver*.
<2> Define a solver config named *regularSolver*.

To inject a specific `SolverManager`, use the `@Qualifier` annotation along with the solver configuration name, e.g., fastSolver.

[tabs]
====
Java::
+
--
[source,java,options="nowrap"]
----
@RestController
@RequestMapping("/path")
public class Resource {

    @Autowired
    @Qualifier("fastSolver")
    SolverManager<...> fastSolver;

    @Autowired
    @Qualifier("regularSolver")
    SolverManager<...> regularSolver;

    ...
}
----
--
Kotlin::
+
--
[source,kotlin,options="nowrap"]
----
@RestController
@RequestMapping("/path")
class Resource {

    @Autowired
    @Qualifier("fastSolver")
    var fastSolver: SolverManager<...>?

    @Autowired
    @Qualifier("regularSolver")
    var regularSolver: SolverManager<...>?

    ...
}
----
--
====

For a more advanced example, let's imagine two different steps for optimizing the school timetabling problem:

1. Initially, a specific group of teachers is designated to teach the available lessons.
2. The next step involves assigning lessons to the rooms.

To configure two different problems, add two XML files containing related planning configurations.

[tabs]
====
teachersSolverConfig.xml::
+
[source,xml,options="nowrap"]
----
<solver xmlns="https://timefold.ai/xsd/solver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://timefold.ai/xsd/solver https://timefold.ai/xsd/solver/solver.xsd">
  <solutionClass>org.acme.schooltimetabling.domain.TeacherToLessonSchedule</solutionClass>
  <entityClass>org.acme.schooltimetabling.domain.Teacher</entityClass>
</solver>
----
roomsSolverConfig.xml::
+
[source,xml,options="nowrap"]
----
<solver xmlns="https://timefold.ai/xsd/solver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://timefold.ai/xsd/solver https://timefold.ai/xsd/solver/solver.xsd">
  <solutionClass>org.acme.schooltimetabling.domain.Timetable</solutionClass>
  <entityClass>org.acme.schooltimetabling.domain.Lesson</entityClass>
</solver>
----
====

Set the solvers with the specific XML files in the `application.properties` file:

[source,properties,options="nowrap"]
----
timefold.solver.teacherSolver.solver-config-xml=teachersSolverConfig.xml // <1>
timefold.solver.roomSolver.solver-config-xml=roomsSolverConfig.xml // <2>
----
<1> Define a solver config named *teacherSolver*.
<2> Define a solver config named *roomSolver*.

Now let's inject both solvers.

[tabs]
====
Java::
+
--
[source,java,options="nowrap"]
----
@PlanningSolution
public class TeacherToLessonSchedule {
    ...
}

@PlanningEntity
public class Teacher {
    ...
}

@RestController
@RequestMapping("/path")
public class Resource {

    @Autowired
    @Qualifier("teacherSolver")
    SolverManager<TeacherToLessonSchedule, String> teacherToLessonScheduleSolverManager;

    @Autowired
    @Qualifier("roomSolver")
    SolverManager<Timetable, String> lessonToRoomTimeslotSolverManager;

    ...
}


----
--
Kotlin::
+
--
[source,kotlin,options="nowrap"]
----

@PlanningSolution
class TeacherToLessonSchedule {
    ...
}

@PlanningEntity
class Teacher {
    ...
}

@RestController
@RequestMapping("/path")
class Resource {

    @Autowired
    @Qualifier("teacherSolver")
    var teacherToLessonScheduleSolverManager: SolverManager<TeacherToLessonSchedule, String>?

    @Autowired
    @Qualifier("roomSolver")
    var lessonToRoomTimeslotSolverManager: SolverManager<Timetable, String>?

    ...
}
----
--
====

**Multi-stage** planning can also be accomplished by using a separate solver configuration for each optimization stage.
