[[releaseNotes]]
= Release Notes

== Upgrade to the latest version

Quickly upgrade your source code to the latest and greatest version of Timefold,
run this command:

Maven:

[source,shell,subs=attributes+]
----
$ mvn org.openrewrite.maven:rewrite-maven-plugin:LATEST:run \
  -Drewrite.recipeArtifactCoordinates=ai.timefold.solver:timefold-solver-migration:{timefold-solver-version} \
  -Drewrite.activeRecipes=ai.timefold.solver.migration.ToLatest
----

Gradle:

[source,shell,subs=attributes+]
----
$ curl https://timefold.ai/product/upgrade/upgrade-timefold.gradle > upgrade-timefold.gradle
$ gradle -Dorg.gradle.jvmargs=-Xmx2G --init-script upgrade-timefold.gradle rewriteRun -DtimefoldSolverVersion={timefold-solver-version}
$ rm upgrade-timefold.gradle
----

It automatically replaces deprecated methods with better alternatives.
Run your tests and commit the changes.

== New & Noteworthy changes

This section contains changes that are of interest to users of Timefold.
It does not mention every code change.
Rather it mentions new features and changes that improve the user experience.

=== 0.9.40

==== New design for the benchmarker report

The HTML report generated by the benchmarker has been significantly modernized.
In place of the old static PNG charts, it now sports interactive responsive charts.
The look and feel of the report has also improved significantly.

==== Constraint Streams `expand()` and `map()`

With the new xref:constraint-streams/constraint-streams.adoc#constraintStreamsExpandingTuples[expand()] functionality,
it is now possible to cache expensive calculations inside the tuples.

The xref:constraint-streams/constraint-streams.adoc#constraintStreamsMappingTuples[expand()] functionality newly
allows mapping into all four cardinalities of streams.