package ai.timefold.solver.core.impl.util;

import static org.assertj.core.api.Assertions.assertThat;

import ai.timefold.solver.core.enterprise.TimefoldSolverEnterpriseService;

import org.junit.jupiter.api.Test;

class SolverVersionUtilsTest {

    // A resource name that never exists, used to deterministically force the manifest fallback path.
    private static final String NONEXISTENT_GIT_PROPERTIES = "does-not-exist-git.properties";

    // ---- stripReleaseCandidate ----

    @Test
    void stripReleaseCandidate_stripsTrailingRcSuffix() {
        assertThat(SolverVersionUtils.stripReleaseCandidate("1.2.3-rc-2")).isEqualTo("1.2.3");
        assertThat(SolverVersionUtils.stripReleaseCandidate("1.2.3-rc-10")).isEqualTo("1.2.3");
    }

    @Test
    void stripReleaseCandidate_leavesNonRcVersionsUnchanged() {
        assertThat(SolverVersionUtils.stripReleaseCandidate("1.2.3")).isEqualTo("1.2.3");
        assertThat(SolverVersionUtils.stripReleaseCandidate("1.2.3-beta-4")).isEqualTo("1.2.3-beta-4");
        assertThat(SolverVersionUtils.stripReleaseCandidate("999-SNAPSHOT")).isEqualTo("999-SNAPSHOT");
        // non-standard spellings pass through verbatim
        assertThat(SolverVersionUtils.stripReleaseCandidate("1.2.3-RC-2")).isEqualTo("1.2.3-RC-2");
        assertThat(SolverVersionUtils.stripReleaseCandidate("1.2.3-rc.2")).isEqualTo("1.2.3-rc.2");
        assertThat(SolverVersionUtils.stripReleaseCandidate("1.2.3-rc")).isEqualTo("1.2.3-rc");
    }

    @Test
    void stripReleaseCandidate_handlesNull() {
        assertThat(SolverVersionUtils.stripReleaseCandidate(null)).isNull();
    }

    // ---- banner (manifest fallback path, forced via a nonexistent resource) ----

    @Test
    void banner_fallsBackToManifestWhenResourceMissing() {
        assertThat(SolverVersionUtils.banner("My Edition", NONEXISTENT_GIT_PROPERTIES, SolverVersionUtilsTest.class))
                // SolverVersionUtilsTest has no manifest version, so falls back to DEVELOPMENT_SNAPSHOT
                .isEqualTo("My Edition " + SolverVersionUtils.DEVELOPMENT_SNAPSHOT);
    }

    // ---- regression test: the actual reported bug ----

    @Test
    void banner_prefersRealGitPropertiesOverAbsentManifestVersion() {
        // SolverVersionUtilsTest.class has no manifest version at all (no JAR, no Implementation-Version).
        // If versionOf(fallbackVersionClass) were still consulted first, this would fall back to
        // "Development Snapshot" -- exactly the shape of the reported native-image bug, where the
        // unreliable manifest-derived value won when it shouldn't have. The real CORE_GIT_PROPERTIES
        // resource (generated by this very build) must win instead.
        var banner = SolverVersionUtils.banner("My Edition", SolverVersionUtils.CORE_GIT_PROPERTIES,
                SolverVersionUtilsTest.class);
        assertThat(banner).doesNotContain(SolverVersionUtils.DEVELOPMENT_SNAPSHOT);
        assertThat(banner).matches("^My Edition v\\S+$");
    }

    @Test
    void bareVersion_prefersRealGitPropertiesOverAbsentManifestVersion() {
        var version = SolverVersionUtils.bareVersion(SolverVersionUtils.CORE_GIT_PROPERTIES, SolverVersionUtilsTest.class);
        assertThat(version).isNotEqualTo("SNAPSHOT");
    }

    // ---- communityBannerWithGitRef (manifest fallback path, forced via a nonexistent resource) ----

    @Test
    void communityBannerWithGitRef_withRef() {
        assertThat(SolverVersionUtils.communityBannerWithGitRef(NONEXISTENT_GIT_PROPERTIES, SolverVersionUtilsTest.class,
                "a1b2c3d"))
                .isEqualTo(SolverVersionUtils.COMMUNITY_NAME + " " + SolverVersionUtils.DEVELOPMENT_SNAPSHOT + " (a1b2c3d)");
    }

    @Test
    void communityBannerWithGitRef_withoutRef() {
        assertThat(SolverVersionUtils.communityBannerWithGitRef(NONEXISTENT_GIT_PROPERTIES, SolverVersionUtilsTest.class,
                null))
                .isEqualTo(SolverVersionUtils.COMMUNITY_NAME + " " + SolverVersionUtils.DEVELOPMENT_SNAPSHOT);
    }

    // ---- enterpriseBannerWithGitRef (manifest fallback path, forced via a nonexistent resource) ----

    @Test
    void enterpriseBannerWithGitRef_bothRefs() {
        assertThat(SolverVersionUtils.enterpriseBannerWithGitRef(NONEXISTENT_GIT_PROPERTIES, SolverVersionUtilsTest.class,
                "aaa1111", "bbb2222"))
                .isEqualTo(SolverVersionUtils.ENTERPRISE_NAME + " " + SolverVersionUtils.DEVELOPMENT_SNAPSHOT
                        + " (core aaa1111, enterprise bbb2222)");
    }

    @Test
    void enterpriseBannerWithGitRef_onlyCoreRef() {
        assertThat(SolverVersionUtils.enterpriseBannerWithGitRef(NONEXISTENT_GIT_PROPERTIES, SolverVersionUtilsTest.class,
                "aaa1111", null))
                .isEqualTo(SolverVersionUtils.ENTERPRISE_NAME + " " + SolverVersionUtils.DEVELOPMENT_SNAPSHOT
                        + " (core aaa1111)");
    }

    @Test
    void enterpriseBannerWithGitRef_onlyEnterpriseRef() {
        assertThat(SolverVersionUtils.enterpriseBannerWithGitRef(NONEXISTENT_GIT_PROPERTIES, SolverVersionUtilsTest.class,
                null, "bbb2222"))
                .isEqualTo(SolverVersionUtils.ENTERPRISE_NAME + " " + SolverVersionUtils.DEVELOPMENT_SNAPSHOT
                        + " (enterprise bbb2222)");
    }

    @Test
    void enterpriseBannerWithGitRef_noRefs() {
        assertThat(SolverVersionUtils.enterpriseBannerWithGitRef(NONEXISTENT_GIT_PROPERTIES, SolverVersionUtilsTest.class,
                null, null))
                .isEqualTo(SolverVersionUtils.ENTERPRISE_NAME + " " + SolverVersionUtils.DEVELOPMENT_SNAPSHOT);
    }

    // ---- resource smoke test ----

    @Test
    void gitRefOf_corePropertiesIsNullOrValidSha() {
        var ref = SolverVersionUtils.gitRefOf(SolverVersionUtils.CORE_GIT_PROPERTIES);
        if (ref != null) {
            assertThat(ref).matches("^[0-9a-f]{7,40}$");
        }
        // null is acceptable (IDE without Maven, no .git directory)
    }

    @Test
    void identifySolverVersionWithGitRef_matchesCommunityPattern() {
        assertThat(TimefoldSolverEnterpriseService.identifySolverVersionWithGitRef())
                .matches("^Timefold Solver Community Edition .+$");
    }

}
