[#springBootQuickStart]
= Spring Boot Quick Start Guide
:doctype: book
:imagesdir: ../..
:sectnums:
:icons: font
include::../../_attributes.adoc[]

:framework: spring-boot
:wiringannotation: @Autowired
:wiringannotationfq: org.springframework.beans.factory.annotation.Autowired
:testannotation: @SpringTest
:testannotationfq: org.springframework.boot.test.context.SpringBootTest
:framework-quickstart-url: {spring-boot-quickstart-url}

This guide walks you through the process of creating a Spring Boot application
with https://timefold.ai[Timefold]'s constraint solving Artificial Intelligence (AI).

include::../shared/whatyoubuild.adoc[]

include::../shared/solutionsourcecode.adoc[]

== Prerequisites

To complete this guide, you need:

include::../shared/java-prerequisites.adoc[]

== The build file and the dependencies

Use https://start.spring.io/[start.spring.io] to generate an application with the following dependencies:

* Spring Web (`spring-boot-starter-web`)
* Timefold Solver (`timefold-solver-spring-boot-starter`)

include::../shared/school-timetabling/school-timetabling-model.adoc[leveloffset=+1]
include::../shared/school-timetabling/school-timetabling-constraints.adoc[leveloffset=+1]
include::../shared/school-timetabling/school-timetabling-solution.adoc[leveloffset=+1]

== Create the solver service

Now you are ready to put everything together and create a REST service.
But solving planning problems on REST threads causes HTTP timeout issues.
Therefore, the Spring Boot starter injects a `SolverManager` instance,
which runs solvers in a separate thread pool
and can solve multiple datasets in parallel.

[tabs]
====
Java::
+
--
Create the `src/main/java/org/acme/schooltimetabling/rest/TimetableController.java` class:

[source,java]
----
package org.acme.schooltimetabling.rest;

import java.util.UUID;
import java.util.concurrent.ExecutionException;

import org.acme.schooltimetabling.domain.Timetable;
import ai.timefold.solver.core.api.solver.SolverJob;
import ai.timefold.solver.core.api.solver.SolverManager;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/timetable")
public class TimetableController {

    @Autowired
    private SolverManager<Timetable, UUID> solverManager;

    @PostMapping
    public Timetable solve(@RequestBody Timetable problem) {
        UUID problemId = UUID.randomUUID();
        // Submit the problem to start solving
        SolverJob<Timetable, UUID> solverJob = solverManager.solve(problemId, problem);
        Timetable solution;
        try {
            // Wait until the solving ends
            solution = solverJob.getFinalBestSolution();
        } catch (InterruptedException | ExecutionException e) {
            throw new IllegalStateException("Solving failed.", e);
        }
        return solution;
    }
}
----
--
Kotlin::
+
--
Create the `src/main/kotlin/org/acme/schooltimetabling/rest/TimetableController.kt` class:

[source,kotlin]
----
package org.acme.schooltimetabling.rest

import ai.timefold.solver.core.api.solver.SolverManager
import org.acme.schooltimetabling.domain.Timetable
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import java.util.UUID
import java.util.concurrent.ExecutionException

@RestController
@RequestMapping("/timetable")
class TimetableController {
    @Autowired
    private val solverManager: SolverManager<Timetable, UUID>? = null

    @PostMapping
    fun solve(@RequestBody problem: Timetable): Timetable {
        val problemId = UUID.randomUUID()
        // Submit the problem to start solving
        val solverJob = solverManager!!.solve(problemId, problem)
        val solution: Timetable
        try {
            // Wait until the solving ends
            solution = solverJob.finalBestSolution
        } catch (e: InterruptedException) {
            throw IllegalStateException("Solving failed.", e)
        } catch (e: ExecutionException) {
            throw IllegalStateException("Solving failed.", e)
        }
        return solution
    }
}
----
--
====

For simplicity's sake, this initial implementation waits for the solver to finish,
which can still cause an HTTP timeout.
The _complete_ implementation avoids HTTP timeouts much more elegantly.

== Set the termination time

Without a termination setting or a `terminationEarly()` event, the solver runs forever.
To avoid that, limit the solving time to five seconds.
That is short enough to avoid the HTTP timeout.

Create the `src/main/resources/application.properties` file:

[source,properties]
----
# The solver runs only for 5 seconds to avoid a HTTP timeout in this simple implementation.
# It's recommended to run for at least 5 minutes ("5m") otherwise.
timefold.solver.termination.spent-limit=5s
----

Timefold Solver returns _the best solution_ found in the available termination time.
Due to xref:optimization-algorithms/overview.adoc#doesTimefoldFindTheOptimalSolution[the nature of NP-hard problems],
the best solution might not be optimal, especially for larger datasets.
Increase the termination time to potentially find a better solution.

== Make the application executable

Package everything into a single executable JAR file driven by a standard Java `main()` method,
replace the `DemoApplication.java` class created by Spring Initializr with the following class:

[tabs]
====
Java::
+
--
[source,java]
----
package org.acme.schooltimetabling;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class TimetableSpringBootApp {

    public static void main(String[] args) {
        SpringApplication.run(TimetableSpringBootApp.class, args);
    }

}
----
--
Kotlin::
+
--
[source,kotlin]
----
package org.acme.schooltimetabling

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
open class TimetableSpringBootApp {

    fun main(args: Array<String>) {
        SpringApplication.run(TimeTableSpringBootApp::class.java, *args)
    }

}
----
--
====

Run that `TimetableSpringBootApp` class as the main class of a normal Java application.

=== Try the application

Now that the application is running, you can test the REST service.
You can use any REST client you wish.
The following example uses the Linux command `curl` to send a POST request:

[source,shell]
----
$ curl -i -X POST http://localhost:8080/timetable -H "Content-Type:application/json" -d '{"timeslots":[{"dayOfWeek":"MONDAY","startTime":"08:30:00","endTime":"09:30:00"},{"dayOfWeek":"MONDAY","startTime":"09:30:00","endTime":"10:30:00"}],"rooms":[{"name":"Room A"},{"name":"Room B"}],"lessons":[{"id":1,"subject":"Math","teacher":"A. Turing","studentGroup":"9th grade"},{"id":2,"subject":"Chemistry","teacher":"M. Curie","studentGroup":"9th grade"},{"id":3,"subject":"French","teacher":"M. Curie","studentGroup":"10th grade"},{"id":4,"subject":"History","teacher":"I. Jones","studentGroup":"10th grade"}]}'
----

After about five seconds, according to the termination spent time defined in your `application.properties`,
the service returns an output similar to the following example:

[source]
----
HTTP/1.1 200
Content-Type: application/json
...

{"timeslots":...,"rooms":...,"lessons":[{"id":1,"subject":"Math","teacher":"A. Turing","studentGroup":"9th grade","timeslot":{"dayOfWeek":"MONDAY","startTime":"08:30:00","endTime":"09:30:00"},"room":{"name":"Room A"}},{"id":2,"subject":"Chemistry","teacher":"M. Curie","studentGroup":"9th grade","timeslot":{"dayOfWeek":"MONDAY","startTime":"09:30:00","endTime":"10:30:00"},"room":{"name":"Room A"}},{"id":3,"subject":"French","teacher":"M. Curie","studentGroup":"10th grade","timeslot":{"dayOfWeek":"MONDAY","startTime":"08:30:00","endTime":"09:30:00"},"room":{"name":"Room B"}},{"id":4,"subject":"History","teacher":"I. Jones","studentGroup":"10th grade","timeslot":{"dayOfWeek":"MONDAY","startTime":"09:30:00","endTime":"10:30:00"},"room":{"name":"Room B"}}],"score":"0hard/0soft"}
----

Notice that your application assigned all four lessons to one of the two time slots and one of the two rooms.
Also notice that it conforms to all hard constraints.
For example, M. Curie's two lessons are in different time slots.

On the server side, the `info` log shows what Timefold Solver did in those five seconds:

[source,options="nowrap"]
----
... Solving started: time spent (33), best score (0hard/0soft), environment mode (PHASE_ASSERT), random (JDK with seed 0).
... Construction Heuristic phase (0) ended: time spent (73), best score (0hard/0soft), move evaluation speed (459/sec), step total (4).
... Local Search phase (1) ended: time spent (5000), best score (0hard/0soft), move evaluation speed (28949/sec), step total (28398).
... Solving ended: time spent (5000), best score (0hard/0soft), move evaluation speed (28524/sec), phase total (2), environment mode (PHASE_ASSERT).
----

[NOTE]
====
In production,
https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#run.run-goal.parameter-details.optimized-launch[optimized launch] should be disabled, since optimized launch disables the https://www.baeldung.com/jvm-tiered-compilation#2c2---server-complier[JVM C2 compiler], considerably decreasing the solver's performance.
====

=== Test the application

A good application includes test coverage.

==== Test the constraints

To test each constraint in isolation, use a `ConstraintVerifier` in unit tests.
It tests each constraint's corner cases in isolation from the other tests,
which lowers maintenance when adding a new constraint with proper test coverage.

include::../shared/constrainttests.adoc[]

This test verifies that the constraint `TimetableConstraintProvider::roomConflict`,
when given three lessons in the same room, where two lessons have the same timeslot,
it penalizes with a match weight of `1`.
So with a constraint weight of `10hard` it would reduce the score by `-10hard`.

In order to inject managed `ConstraintVerifier<TimetableConstraintProvider, Timetable>` instances, we need a bean definition source class.

[tabs]
====
Java::
+
--
[source,java]
----
package org.acme.schooltimetabling.config;

import ai.timefold.solver.core.api.score.stream.test.ConstraintVerifier;
import org.acme.schooltimetabling.domain.Lesson;
import org.acme.schooltimetabling.domain.Timetable;
import org.acme.schooltimetabling.solver.TimetableConstraintProvider;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;

@TestConfiguration
public class ConstraintConfig {

    @Bean
    public ConstraintVerifier<TimetableConstraintProvider, Timetable> buildConstraintVerifier() {
        return ConstraintVerifier.build(new TimetableConstraintProvider(), Timetable.class, Lesson.class);
    }
}
----
--
Kotlin::
+
--
[source,kotlin]
----
package org.acme.schooltimetabling.config

import ai.timefold.solver.core.api.score.stream.test.ConstraintVerifier;
import org.acme.schooltimetabling.domain.Lesson
import org.acme.schooltimetabling.domain.Timetable
import org.acme.schooltimetabling.solver.TimetableConstraintProvider
import org.springframework.boot.test.context.TestConfiguration
import org.springframework.context.annotation.Bean

@TestConfiguration
open class ConstraintConfig {
    @Bean
    open fun buildConstraintVerifier(): ConstraintVerifier<TimetableConstraintProvider, Timetable> {
        return ConstraintVerifier.build(TimetableConstraintProvider(), Timetable::class.java, Lesson::class.java)
    }
}
----
--
====


Notice how `ConstraintVerifier` ignores the constraint weight during testing - even
if those constraint weights are hard coded in the `ConstraintProvider` - because
constraints weights change regularly before going into production.
This way, constraint weight tweaking does not break the unit tests.

==== Test the solver

In a JUnit test, generate a test dataset and send it to the `TimetableController` to solve.

[tabs]
====
Java::
+
--
Create the `src/test/java/org/acme/schooltimetabling/rest/TimetableControllerTest.java` class:

[source,java]
----
package org.acme.schooltimetabling.rest;

import ai.timefold.solver.core.api.solver.SolverStatus;
import io.restassured.http.ContentType;
import org.acme.schooltimetabling.domain.Timetable;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import java.time.Duration;

import static io.restassured.RestAssured.get;
import static io.restassured.RestAssured.given;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(properties = {
        // Effectively disable spent-time termination in favor of the best-score-limit
        "timefold.solver.termination.spent-limit=1h",
        "timefold.solver.termination.best-score-limit=0hard/*soft" },
        webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
class TimetableControllerTest {

    @Test
    void solveDemoDataUntilFeasible() {
        Timetable testTimetable = // setup test data

        Timetable solution = given()
                .contentType(ContentType.JSON)
                .body(testTimetable)
                .expect().contentType(ContentType.TEXT)
                .when().post("/timetables")
                .then()
                .statusCode(201)
                .extract()
                .as(Timetable.class);

        assertNotNull(solution.getLessons());
        assertNotNull(solution.getTimeslots());
        assertNotNull(solution.getRooms());
        assertNotNull(solution.getLessons().get(0).getRoom());
        assertNotNull(solution.getLessons().get(0).getTimeslot());
        assertTrue(solution.getScore().isFeasible());
    }

}
----
--
Kotlin::
+
--
Create the `src/test/kotlin/org/acme/schooltimetabling/rest/TimetableControllerTest.kt` class:

[source,kotlin]
----
package org.acme.schooltimetabling.rest

import ai.timefold.solver.core.api.solver.SolverStatus
import io.restassured.RestAssured
import io.restassured.http.ContentType
import org.acme.schooltimetabling.domain.Timetable
import org.awaitility.Awaitility
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest
import java.time.Duration

@SpringBootTest(
    properties = [ // Effectively disable spent-time termination in favor of the best-score-limit
        "timefold.solver.termination.spent-limit=1h",
        "timefold.solver.termination.best-score-limit=0hard/*soft"],
    webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT
)
internal class TimetableControllerTest {
    @Test
    fun solveDemoDataUntilFeasible() {
        val testTimetable = //setup test data

        val solution = RestAssured.given()
            .contentType(ContentType.JSON)
            .body(testTimetable)
            .expect().contentType(ContentType.TEXT)
            .`when`().post("/timetables")
            .then()
            .statusCode(201)
            .extract()
            .as(Timetable.class)

        Assertions.assertNotNull(solution.lessons)
        Assertions.assertNotNull(solution.timeslots)
        Assertions.assertNotNull(solution.rooms)
        Assertions.assertNotNull(solution.lessons[0].room)
        Assertions.assertNotNull(solution.lessons[0].timeslot)
        Assertions.assertTrue(solution.score.isFeasible)
    }
}
----
--
====


This test verifies that after solving, all lessons are assigned to a time slot and a room.
It also verifies that it found a feasible solution (no hard constraints broken).

Normally, the solver finds a feasible solution in less than 200 milliseconds.
Notice how the `@SpringBootTest` annotation's `properties` property overwrites the solver termination during tests
to terminate as soon as a feasible solution (`0hard/*soft`) is found.
This avoids hard coding a solver time, because the unit test might run on arbitrary hardware.
This approach ensures that the test runs long enough to find a feasible solution, even on slow machines.
But it does not run a millisecond longer than it strictly must, even on fast machines.

=== Logging

When adding constraints in your `ConstraintProvider`,
keep an eye on the _move evaluation speed_ in the `info` log,
after solving for the same amount of time, to assess the performance impact:

[source]
----
... Solving ended: ..., move evaluation speed (29455/sec), ...
----

To understand how Timefold Solver is solving your problem internally,
change the logging in the `application.properties` file or with a `-D` system property:

[source,properties]
----
logging.level.ai.timefold.solver=debug
----

Use `debug` logging to show every _step_:

[source,options="nowrap"]
----
... Solving started: time spent (67), best score (0hard/0soft), environment mode (PHASE_ASSERT), random (JDK with seed 0).
...     CH step (0), time spent (128), score (0hard/0soft), selected move count (15), picked move ([Math(101) {null -> Room A}, Math(101) {null -> MONDAY 08:30}]).
...     CH step (1), time spent (145), score (0hard/0soft), selected move count (15), picked move ([Physics(102) {null -> Room A}, Physics(102) {null -> MONDAY 09:30}]).
...
----

Use `trace` logging to show every _step_ and every _move_ per step.

== Summary

Congratulations!
You have just developed a Spring application with https://timefold.ai[Timefold]!

Next Steps:

- For a full implementation with a web UI, check out {spring-boot-quickstart-url}[the Spring-boot quickstart source code].
- Check out more information about Timefold's integration with Spring in our xref:../integration/integration.adoc#integrationWithSpringBoot[Integration documentation].
