[#upgradingTimefoldSolverOverview]
= Upgrading Timefold Solver: Overview
:doctype: book
:sectnums:
:icons: font

In this section, you will:

- Learn how to upgrade to the latest version of Timefold Solver automatically.
- Find a detailed upgrade recipe for every major change we make to the Timefold Solver APIs.

To find out what's new in the latest version of Timefold Solver,
see the https://github.com/TimefoldAI/timefold-solver/releases[Timefold Solver release notes]
in our GitHub repository,
read https://timefold.ai/blog[our blog],
or subscribe to our newsletter.

== Backwards compatibility

Timefold Solver separates its API from its implementation:

* **Public API**: All classes under these `api` and `config` namespaces are 100% *backwards compatible* in future minor and hotfix releases:
** `ai.timefold.solver.core.api`
** `ai.timefold.solver.benchmark.api`
** `ai.timefold.solver.test.api`
** `ai.timefold.solver.*.api`
** `ai.timefold.solver.core.config`
** `ai.timefold.solver.benchmark.config`
* **Implementation classes**: All other classes are _not_ backwards compatible.
They will change in future major or minor releases,
but probably not in hotfix releases.

Backwards incompatible changes for a new major version are clearly documented in xref:upgrading-timefold-solver/upgrade-from-v1.adoc#manualUpgrade[the upgrade recipe].


