[#upgradeToLatestVersion]
= Upgrade to the latest version
:doctype: book
:sectnums:
:icons: font

Timefold Solver public APIs are backwards compatible,
but users often also use internal Solver classes which are not guaranteed to stay compatible.
This upgrade recipe minimizes the pain to upgrade your code
and to take advantage of the newest features in Timefold Solver.

[#automaticUpgradeToLatestVersion]
== Automatic upgrade to the latest version

For many of the upgrade steps mentioned later,
we actually provide an upgrade tool that can automatically apply those changes to Java files.
This tool is based on OpenRewrite and can be run as a Maven or Gradle plugin.
To run the tool, execute the following command in your project directory:

[tabs]
====
Maven::
+
--
[source,shell,subs=attributes+]
----
mvn org.openrewrite.maven:rewrite-maven-plugin:{rewrite-maven-plugin-version}:run -Drewrite.recipeArtifactCoordinates=ai.timefold.solver:timefold-solver-migration:{timefold-solver-version} -Drewrite.activeRecipes=ai.timefold.solver.migration.ToLatest
----
--

Gradle::
+
--
[source,shell,subs=attributes+]
----
curl https://raw.githubusercontent.com/TimefoldAI/timefold-solver/refs/tags/v{timefold-solver-version}/migration/upgrade-timefold.gradle > upgrade-timefold.gradle ; gradle -Dorg.gradle.jvmargs=-Xmx2G --init-script upgrade-timefold.gradle rewriteRun -DtimefoldSolverVersion={timefold-solver-version} ; rm upgrade-timefold.gradle
----
--
====

include::framework-version-warning.adoc[leveloffset=+1]

Having done that, you can check the local changes and commit them.
Note that none of the upgrade steps could be automatically applied,
and it may still be worth your while to read the rest the upgrade recipe below.

For the time being, Kotlin users need to follow the upgrade recipe and apply the steps manually.

[#manualUpgrade]
== Manual upgrade recipe

Every upgrade note indicates how likely your code will be affected by that change:

- icon:magic[] *Automated*: Can be applied automatically using our <<automaticUpgradeToLatestVersion,upgrade tooling>>.
- icon:exclamation-triangle[role=red] *Major*: Likely to affect your code.
- icon:info-circle[role=yellow] *Minor*: Lesser used feature, unlikely to affect your code.
- icon:eye[] *Recommended*: Does not affect backwards compatibility, but you probably want to be aware.

The upgrade recipe often lists the changes as they apply to Java code.
We kindly ask Kotlin users to translate the changes accordingly.
