package ai.timefold.solver.core.preview.api.move.builtin;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import ai.timefold.solver.core.api.solver.SolutionManager;
import ai.timefold.solver.core.preview.api.neighborhood.test.NeighborhoodTester;
import ai.timefold.solver.core.testdomain.list.TestdataListEntity;
import ai.timefold.solver.core.testdomain.list.TestdataListSolution;
import ai.timefold.solver.core.testdomain.list.pinned.TestdataPinnedListEntity;
import ai.timefold.solver.core.testdomain.list.pinned.TestdataPinnedListSolution;
import ai.timefold.solver.core.testdomain.list.unassignedvar.TestdataAllowsUnassignedValuesListEntity;
import ai.timefold.solver.core.testdomain.list.unassignedvar.TestdataAllowsUnassignedValuesListSolution;
import ai.timefold.solver.core.testdomain.list.valuerange.TestdataListEntityProvidingEntity;
import ai.timefold.solver.core.testdomain.list.valuerange.TestdataListEntityProvidingSolution;
import ai.timefold.solver.core.testdomain.list.valuerange.unassignedvar.TestdataListUnassignedEntityProvidingEntity;
import ai.timefold.solver.core.testdomain.list.valuerange.unassignedvar.TestdataListUnassignedEntityProvidingSolution;

import org.jspecify.annotations.NullMarked;
import org.junit.jupiter.api.Test;

@NullMarked
class ListChangeMoveProviderTest {

    @Test
    void pinnedEntitySkipped() {
        var solutionMetaModel = TestdataPinnedListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataPinnedListEntity.class)
                .listVariable();

        var solution = TestdataPinnedListSolution.generateInitializedSolution(2, 2);
        var firstEntity = solution.getEntityList().getFirst();
        var secondEntity = solution.getEntityList().get(1);
        firstEntity.setPinned(true);

        // firstEntity is pinned -> values can't leave it AND nothing can be moved to it.
        // secondEntity has one value but its only valid destination is firstEntity (which is pinned).
        NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
                .using(solution)
                .producesNoneOf(
                        Moves.change(variableMetaModel, secondEntity, 0, firstEntity, 0),
                        Moves.change(variableMetaModel, firstEntity, 0, secondEntity, 0));
    }

    @Test
    void fromSolution() {
        var solutionMetaModel = TestdataListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataListEntity.class)
                .listVariable();

        var solution = TestdataListSolution.generateUninitializedSolution(2, 2);
        var e1 = solution.getEntityList().get(0);
        var e2 = solution.getEntityList().get(1);
        var initiallyAssignedValue = solution.getValueList().get(1);
        e2.getValueList().add(initiallyAssignedValue);
        SolutionManager.updateShadowVariables(solution);

        // Assign moves are not generated by ListChangeMoveProvider.
        // Unassign moves are not generated by ListChangeMoveProvider.
        // Change move is generated for moving the initially assigned value from e2 to e1.
        var context = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
                .using(solution);
        context.producesAllOf(Moves.change(variableMetaModel, e2, 0, e1, 0));
        context.producesNoneOf(
                Moves.change(variableMetaModel, e2, 0, e2, 0), // No-op: same position.
                Moves.change(variableMetaModel, e2, 0, e2, 1)); // No-op: only element, moving after itself.
    }

    @Test
    void fromEntity() {
        var solutionMetaModel = TestdataListEntityProvidingSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataListEntityProvidingEntity.class)
                .listVariable();

        var solution = TestdataListEntityProvidingSolution.generateSolution();
        var e1 = solution.getEntityList().getFirst();
        e1.getValueList().clear();
        var e2 = solution.getEntityList().get(1);
        var initiallyAssignedValue = e2.getValueRange().getFirst();
        e2.getValueList().add(initiallyAssignedValue);
        SolutionManager.updateShadowVariables(solution);

        // v1 can be moved from e2 to e1, because it's in the range for both.
        // v2 and v3 are unassigned; assign moves are not generated by ListChangeMoveProvider.
        var context = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
                .using(solution);
        context.producesAllOf(Moves.change(variableMetaModel, e2, 0, e1, 0));
        context.producesNoneOf(
                Moves.change(variableMetaModel, e2, 0, e2, 0),
                Moves.change(variableMetaModel, e2, 0, e2, 1));
    }

    @Test
    void fromEntityAllowsUnassigned() {
        var solutionMetaModel = TestdataListUnassignedEntityProvidingSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataListUnassignedEntityProvidingEntity.class)
                .listVariable();

        var solution = TestdataListUnassignedEntityProvidingSolution.generateSolution();
        var e1 = solution.getEntityList().get(0);
        var e2 = solution.getEntityList().get(1);
        var v1 = solution.getValueList().getFirst();
        e2.getValueList().add(v1);

        // v1 is assigned to e2 and can be moved to e1, because it's in the range for both.
        // crossingNull=false: unassign and assign moves are not generated.
        // v2 and v3 are unassigned; assign moves are not generated by ListChangeMoveProvider.
        var context = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel, false), solutionMetaModel)
                .using(solution);
        context.producesAllOf(Moves.change(variableMetaModel, e2, 0, e1, 0));
        context.producesNoneOf(
                Moves.change(variableMetaModel, e2, 0, e2, 0),
                Moves.change(variableMetaModel, e2, 0, e2, 1));
    }

    @Test
    void fromSolutionAllowsUnassigned() {
        var solutionMetaModel = TestdataAllowsUnassignedValuesListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataAllowsUnassignedValuesListEntity.class)
                .listVariable();
        var solution = TestdataAllowsUnassignedValuesListSolution.generateUninitializedSolution(2, 2);
        var e1 = solution.getEntityList().get(0);
        var e2 = solution.getEntityList().get(1);
        var v1 = solution.getValueList().getFirst();
        e2.getValueList().add(v1);
        SolutionManager.updateShadowVariables(solution);

        // v1 is assigned to e2 and can be moved to e1.
        // crossingNull=false: unassign and assign moves are not generated.
        // v2 is unassigned; assign moves are not generated by ListChangeMoveProvider.
        var context = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel, false), solutionMetaModel)
                .using(solution);
        context.producesAllOf(Moves.change(variableMetaModel, e2, 0, e1, 0));
        context.producesNoneOf(
                Moves.change(variableMetaModel, e2, 0, e2, 0),
                Moves.change(variableMetaModel, e2, 0, e2, 1));
    }

    @Test
    void crossingNullDefaultsToAllowsUnassignedValues() {
        var solutionMetaModel = TestdataAllowsUnassignedValuesListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataAllowsUnassignedValuesListEntity.class)
                .listVariable();

        assertThat(variableMetaModel.allowsUnassignedValues()).isTrue();
        // The single-argument constructor defaults crossingNull to the variable's own allowsUnassignedValues(),
        // mirroring ChangeMoveProvider's own constructor exactly.
        assertThatCode(() -> new ListChangeMoveProvider<>(variableMetaModel, true)).doesNotThrowAnyException();
    }

    @Test
    void crossingNullTrueRequiresAllowsUnassignedValues() {
        var solutionMetaModel = TestdataListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataListEntity.class)
                .listVariable();

        assertThat(variableMetaModel.allowsUnassignedValues()).isFalse();
        assertThatThrownBy(() -> new ListChangeMoveProvider<>(variableMetaModel, true))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("crossingNull");
    }

    @Test
    void crossingNullTrueProducesAssignAndUnassign() {
        var solutionMetaModel = TestdataAllowsUnassignedValuesListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataAllowsUnassignedValuesListEntity.class)
                .listVariable();
        var solution = TestdataAllowsUnassignedValuesListSolution.generateUninitializedSolution(2, 2);
        var e1 = solution.getEntityList().get(0);
        var e2 = solution.getEntityList().get(1);
        var assignedValue = solution.getValueList().get(0);
        var unassignedValue = solution.getValueList().get(1);
        e1.getValueList().add(assignedValue);
        SolutionManager.updateShadowVariables(solution);

        // crossingNull=true: the assigned value can be unassigned, and the unassigned value can be assigned.
        var context = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel, true), solutionMetaModel)
                .using(solution);
        context.producesAllOf(
                Moves.unassign(variableMetaModel, e1, 0),
                Moves.assign(variableMetaModel, unassignedValue, e2, 0));
    }

    @Test
    void crossingNullFalseProducesNeitherAssignNorUnassign() {
        var solutionMetaModel = TestdataAllowsUnassignedValuesListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataAllowsUnassignedValuesListEntity.class)
                .listVariable();
        var solution = TestdataAllowsUnassignedValuesListSolution.generateUninitializedSolution(2, 2);
        var e1 = solution.getEntityList().get(0);
        var e2 = solution.getEntityList().get(1);
        var assignedValue = solution.getValueList().get(0);
        var unassignedValue = solution.getValueList().get(1);
        e1.getValueList().add(assignedValue);
        SolutionManager.updateShadowVariables(solution);

        var context = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel, false), solutionMetaModel)
                .using(solution);
        context.producesNoneOf(
                Moves.unassign(variableMetaModel, e1, 0),
                Moves.assign(variableMetaModel, unassignedValue, e2, 0));
    }

}
