package ai.timefold.solver.core.preview.api.move.builtin;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.SoftAssertions.assertSoftly;

import java.util.List;

import ai.timefold.solver.core.api.solver.SolutionManager;
import ai.timefold.solver.core.preview.api.move.Move;
import ai.timefold.solver.core.preview.api.neighborhood.test.NeighborhoodTester;
import ai.timefold.solver.core.testdomain.list.TestdataListEntity;
import ai.timefold.solver.core.testdomain.list.TestdataListSolution;
import ai.timefold.solver.core.testdomain.list.unassignedvar.TestdataAllowsUnassignedValuesListEntity;
import ai.timefold.solver.core.testdomain.list.unassignedvar.TestdataAllowsUnassignedValuesListSolution;
import ai.timefold.solver.core.testdomain.list.valuerange.TestdataListEntityProvidingEntity;
import ai.timefold.solver.core.testdomain.list.valuerange.TestdataListEntityProvidingSolution;
import ai.timefold.solver.core.testdomain.list.valuerange.unassignedvar.TestdataListUnassignedEntityProvidingEntity;
import ai.timefold.solver.core.testdomain.list.valuerange.unassignedvar.TestdataListUnassignedEntityProvidingSolution;

import org.jspecify.annotations.NullMarked;
import org.junit.jupiter.api.Test;

@NullMarked
class ListChangeMoveProviderTest {

    @Test
    void fromSolution() {
        var solutionMetaModel = TestdataListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataListEntity.class)
                .listVariable();

        var solution = TestdataListSolution.generateUninitializedSolution(2, 2);
        var e1 = solution.getEntityList().get(0);
        var e2 = solution.getEntityList().get(1);
        var initiallyAssignedValue = solution.getValueList().get(1);
        e2.getValueList().add(initiallyAssignedValue);
        SolutionManager.updateShadowVariables(solution);

        var moveList = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
                .using(solution)
                .getMovesAsList();
        assertThat(moveList).hasSize(1);

        // Assign moves are not generated by ListChangeMoveProvider.
        // Unassign moves are not generated by ListChangeMoveProvider.
        // Change move is generated for moving the initially assigned value from e2 to e1.

        var move1 = getListChangeMove(moveList, 0);
        assertSoftly(softly -> {
            softly.assertThat(move1.getSourceEntity()).isEqualTo(e2);
            softly.assertThat(move1.getSourceIndex()).isEqualTo(0);
            softly.assertThat(move1.getDestinationEntity()).isEqualTo(e1);
            softly.assertThat(move1.getDestinationIndex()).isEqualTo(0);
            softly.assertThat(move1.getPlanningEntities())
                    .containsExactly(e2, e1);
            softly.assertThat(move1.getPlanningValues())
                    .containsExactly(initiallyAssignedValue);
        });
    }

    @Test
    void fromEntity() {
        var solutionMetaModel = TestdataListEntityProvidingSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataListEntityProvidingEntity.class)
                .listVariable();

        var solution = TestdataListEntityProvidingSolution.generateSolution();
        var e1 = solution.getEntityList().getFirst();
        var v1 = solution.getValueList().getFirst();
        e1.getValueList().clear();
        var e2 = solution.getEntityList().get(1);
        var initiallyAssignedValue = e2.getValueRange().getFirst();
        e2.getValueList().add(initiallyAssignedValue);
        SolutionManager.updateShadowVariables(solution);

        var moveList = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
                .using(solution)
                .getMovesAsList();
        assertThat(moveList).hasSize(1);

        // v1 can be moved from e2 to e1, because it's in the range for both.
        // v2 and v3 are unassigned; assign moves are not generated by ListChangeMoveProvider.

        var move1 = getListChangeMove(moveList, 0);
        assertSoftly(softly -> {
            softly.assertThat(move1.getSourceEntity()).isEqualTo(e2);
            softly.assertThat(move1.getSourceIndex()).isEqualTo(0);
            softly.assertThat(move1.getDestinationEntity()).isEqualTo(e1);
            softly.assertThat(move1.getDestinationIndex()).isEqualTo(0);
            softly.assertThat(move1.getPlanningEntities())
                    .containsExactly(e2, e1);
            softly.assertThat(move1.getPlanningValues())
                    .containsExactly(v1);
        });
    }

    @Test
    void fromEntityAllowsUnassigned() {
        var solutionMetaModel = TestdataListUnassignedEntityProvidingSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataListUnassignedEntityProvidingEntity.class)
                .listVariable();

        var solution = TestdataListUnassignedEntityProvidingSolution.generateSolution();
        var e1 = solution.getEntityList().get(0);
        var e2 = solution.getEntityList().get(1);
        var v1 = solution.getValueList().getFirst();
        e2.getValueList().add(v1);

        var moveList = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
                .using(solution)
                .getMovesAsList();
        assertThat(moveList).hasSize(1);

        // v1 is assigned to e2 and can be moved to e1, because it's in the range for both.
        // Unassign moves are not generated by ListChangeMoveProvider.
        // v2 and v3 are unassigned; assign moves are not generated by ListChangeMoveProvider.

        var move1 = getListChangeMove(moveList, 0);
        assertSoftly(softly -> {
            softly.assertThat(move1.getSourceEntity()).isEqualTo(e2);
            softly.assertThat(move1.getSourceIndex()).isEqualTo(0);
            softly.assertThat(move1.getDestinationEntity()).isEqualTo(e1);
            softly.assertThat(move1.getDestinationIndex()).isEqualTo(0);
            softly.assertThat(move1.getPlanningEntities())
                    .containsExactly(e2, e1);
            softly.assertThat(move1.getPlanningValues())
                    .containsExactly(v1);
        });
    }

    @Test
    void fromSolutionAllowsUnassigned() {
        var solutionMetaModel = TestdataAllowsUnassignedValuesListSolution.buildMetaModel();
        var variableMetaModel = solutionMetaModel.genuineEntity(TestdataAllowsUnassignedValuesListEntity.class)
                .listVariable();
        var solution = TestdataAllowsUnassignedValuesListSolution.generateUninitializedSolution(2, 2);
        var e1 = solution.getEntityList().get(0);
        var e2 = solution.getEntityList().get(1);
        var v1 = solution.getValueList().getFirst();
        e2.getValueList().add(v1);
        SolutionManager.updateShadowVariables(solution);

        var moveList = NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
                .using(solution)
                .getMovesAsList();
        assertThat(moveList).hasSize(1);

        // v1 is assigned to e2 and can be moved to e1.
        // Unassign moves are not generated by ListChangeMoveProvider.
        // v2 is unassigned; assign moves are not generated by ListChangeMoveProvider.

        var move1 = getListChangeMove(moveList, 0);
        assertSoftly(softly -> {
            softly.assertThat(move1.getSourceEntity()).isEqualTo(e2);
            softly.assertThat(move1.getSourceIndex()).isEqualTo(0);
            softly.assertThat(move1.getDestinationEntity()).isEqualTo(e1);
            softly.assertThat(move1.getDestinationIndex()).isEqualTo(0);
            softly.assertThat(move1.getPlanningEntities())
                    .containsExactly(e2, e1);
            softly.assertThat(move1.getPlanningValues())
                    .containsExactly(v1);
        });
    }

    private static <Solution_, Entity_, Value_> ListChangeMove<Solution_, Entity_, Value_>
            getListChangeMove(List<Move<Solution_>> moveList, int index) {
        return (ListChangeMove<Solution_, Entity_, Value_>) moveList.get(index);
    }

}
