package ai.timefold.solver.quarkus.constraints;
    dialect "java"

import ai.timefold.solver.core.api.score.buildin.simple.SimpleScoreHolder;

import ai.timefold.solver.quarkus.drl.it.domain.TestdataQuarkusEntity;

global SimpleScoreHolder scoreHolder;

rule "Don't assign 2 entities the same value."
    when
        $a : TestdataQuarkusEntity($fullValue: fullValue)
        TestdataQuarkusEntity($fullValue == fullValue, this != $a)
    then
        scoreHolder.addConstraintMatch(kcontext, -1);
end
