########################
# Timefold application info
########################
timefold.model.contact.email=info@timefold.ai
timefold.model.contact.name=Timefold BV
timefold.model.contact.url=https://timefold.ai
timefold.model.name=Integration Tests - Simplified Employee Shift Scheduling model
timefold.model.id=integration-tests-simplified-employee-shift-scheduling

%test.timefold.model.termination.best-score-limit=0hard/0medium/*soft
%test.timefold.model.api-version=v1