# Updates Spring Initializr when a new version of Timefold Solver is released.

name: Update Spring Initializr
on:
  push:
    tags:
      - 'v*'
  pull_request: # Remove when tested
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Timefold Solver
        uses: actions/checkout@v4
        with:
          path: timefold-solver
          tags: true
          fetch-depth: 0

      - name: Set env
        shell: bash
        run: |
          cd timefold-solver
          echo "TIMEFOLD_SOLVER_RELEASE_TAG=$(gh release list | head -n 1 | cut -f 3)" >> $GITHUB_ENV
          echo "TIMEFOLD_SOLVER_RELEASE=$(echo $TIMEFOLD_SOLVER_RELEASE_TAG | tail -c +2)" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Checkout Spring Initializr
        uses: actions/checkout@v4
        with:
          repository: spring-io/start.spring.io
          path: spring-initializr
          fetch-depth: 0

      - name: Set the new version and create the PR
        env:
          GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          SPRING_INITIALIZR_YAML_FILE_PATH: "start-site/src/main/resources/application.yml"
        shell: bash
        run: |
          echo "Will bump Spring Initializr to $TIMEFOLD_SOLVER_RELEASE"
          cd ../spring-initializr          
          git config user.name "Timefold Release Bot"
          git config user.email "release@timefold.ai"
          git checkout -b $TIMEFOLD_SOLVER_RELEASE_TAG
          ../timefold-solver/.github/scripts/sprint_initializr_bump_solver.sh
          git add $SPRING_INITIALIZR_YAML_FILE_PATH
          git commit -m "Upgrade to Timefold Solver $TIMEFOLD_SOLVER_RELEASE" 
          #gh pr create --title "Upgrade to Timefold Solver $TIMEFOLD_SOLVER_RELEASE" --body "CC @triceo"