package ai.timefold.solver.core.impl.domain.common;

import ai.timefold.solver.core.api.domain.variable.PlanningVariable;

/**
 * Determines how members (fields and methods) of the domain (for example the {@link PlanningVariable planner variable})
 * are accessed.
 */
public enum DomainAccessType {
    /**
     * Determine what domain access type to use automatically.
     * <p>
     * This is the default.
     */
    AUTO,

    /**
     * Use reflection to read/write members (fields and methods) of the domain.
     * <p>
     * When used in a modulepath, the module must be open.
     * When used in GraalVM, the domain must be open for reflection.
     */
    FORCE_REFLECTION,

    /**
     * Use Gizmo generated bytecode to access members (fields and methods) to avoid reflection
     * for additional performance.
     * <p>
     * This is the default when the application is run inside a JVM and not a native image.
     */
    FORCE_GIZMO
}
